from django.urls import path
from . import views

urlpatterns = [
    path('oldinfo/', views.show_old),
    path('guardianinfo/', views.show_guardian),
    path('carerinfo/', views.show_carer),
    path('goods/', views.show_goods),
    path('order/', views.show_order),
    path('dailycheck/', views.show_dailychek),
    path('dailycall/', views.show_dailycall),
    path('dailysched/', views.show_dailyschedule),
    path('actcontent/', views.show_actcontent),
    path('actplace/',views.show_actplace),
    path('actarran/', views.show_actarrange),

    path('oldadd/', views.old_add),
    path('guardianadd/', views.guardian_add),
    path('careradd/', views.carer_add),
    path('goodsadd/', views.goods_add),
    path('orderadd/', views.order_add),
    path('checkadd/', views.check_add),
    path('calladd/', views.call_add),
    path('schedadd/', views.schedule_add),
    path('actcadd/', views.activity_add),
    path('actpadd/', views.place_add),
    path('actarradd/', views.arrange_add),

    path('oldedit/', views.old_edit),
    path('guardianedit/', views.guardian_edit),
    path('careredit/', views.carer_edit),
    path('goodsedit/', views.goods_edit),
    path('orderedit/', views.order_edit),
    path('checkedit/', views.check_edit),
    path('calledit/', views.call_edit),
    path('schedit/', views.schedule_edit),
    path('actcedit/', views.activity_edit),
    path('actpedit/', views.place_edit),
    path('actaedit/', views.arrange_edit),

    path('oldelete/', views.old_delete),
    path('guardiandelete/', views.guardian_delete),
    path('carerdelete/', views.carer_delete),
    path('goodsdelete/', views.goods_delete),
    path('orderdelete/', views.order_delete),
    path('checkdelete/', views.check_delete),
    path('calldelete/', views.call_delete),
    path('schedelete/', views.schedule_delete),
    path('actdelete/', views.act_delete),
    path('placedelete/', views.place_delete),
    path('arrandelete/', views.arrange_delete),

    path('oldsearch/', views.old_search),
    path ('guardiansearch/', views.guardian_search),
    path ('carersearch/', views.carer_search),
    path ('goodsearch/', views.goods_search),
    path ('ordersearch/', views.order_search),
    path ('checksearch/', views.check_search),
    path ('callsearch/', views.call_search),
    path ('schedsearch/', views.schedule_search),
    path ('actsearch/', views.activity_search),
    path ('placesearch/', views.place_search),

    path('', views.show_old),

]