# Generated by Django 3.1.6 on 2021-03-10 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=20)),
                ('carer', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('idcard', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tele', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'carer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('drugs', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'diagnoses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoSd',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'go_sd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('idcard', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('tele', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'guardian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Old',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('idcard', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('guardian1', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian2', models.CharField(blank=True, max_length=20, null=True)),
                ('bankcard', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('goodsid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('orderid', models.CharField(max_length=20)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=20)),
                ('actid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestmodelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'testmodel_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('todo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'to_do',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arrangeact',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TestModel.activity')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('peonum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arrangeact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailycheck',
            fields=[
                ('oid', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TestModel.old')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('bloodpressure', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('pulse', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('condition', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dailycheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oc',
            fields=[
                ('oid', models.OneToOneField(db_column='oid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TestModel.old')),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_goods_num', models.IntegerField(default=1)),
                ('C_is_select', models.BooleanField(default=True)),
                ('C_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.goods')),
                ('C_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.old')),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
    ]
